[Icon Theme]
Name=Retrograde
Comment=Pixel icons in the colours of the Retrograde sunset
Inherits=breeze-dark,hicolor
Example=folder
FollowsColorScheme=true
DisplayDepth=32
Directories=applets/16,applets/scalable,apps/16,apps/scalable,categories/16,categories/scalable,devices/16,devices/scalable,mimetypes/16,mimetypes/scalable,places/16,places/scalable,preferences/16,preferences/scalable,status/16,status/scalable,breeze/actions/16,breeze/actions/22,breeze/actions/24,breeze/actions/32,breeze/applets/48,breeze/apps/16,breeze/apps/22,breeze/apps/32,breeze/categories/22,breeze/devices/16,breeze/devices/22,breeze/devices/32,breeze/emotes/22,breeze/mimetypes/16,breeze/mimetypes/22,breeze/mimetypes/32,breeze/mimetypes/64,breeze/places/16,breeze/places/22,breeze/preferences/22,breeze/preferences/32,breeze/status/16,breeze/status/22,breeze/status/24,breeze/status/32

[applets/16]
Size=16
Context=Applications
Type=Scalable
MinSize=8
MaxSize=22

[applets/scalable]
Size=48
Context=Applications
Type=Scalable
MinSize=23
MaxSize=512

[apps/16]
Size=16
Context=Applications
Type=Scalable
MinSize=8
MaxSize=22

[apps/scalable]
Size=48
Context=Applications
Type=Scalable
MinSize=23
MaxSize=512

[categories/16]
Size=16
Context=Categories
Type=Scalable
MinSize=8
MaxSize=22

[categories/scalable]
Size=48
Context=Categories
Type=Scalable
MinSize=23
MaxSize=512

[devices/16]
Size=16
Context=Devices
Type=Scalable
MinSize=8
MaxSize=22

[devices/scalable]
Size=48
Context=Devices
Type=Scalable
MinSize=23
MaxSize=512

[mimetypes/16]
Size=16
Context=MimeTypes
Type=Scalable
MinSize=8
MaxSize=22

[mimetypes/scalable]
Size=48
Context=MimeTypes
Type=Scalable
MinSize=23
MaxSize=512

[places/16]
Size=16
Context=Places
Type=Scalable
MinSize=8
MaxSize=22

[places/scalable]
Size=48
Context=Places
Type=Scalable
MinSize=23
MaxSize=512

[preferences/16]
Size=16
Context=Applications
Type=Scalable
MinSize=8
MaxSize=22

[preferences/scalable]
Size=48
Context=Applications
Type=Scalable
MinSize=23
MaxSize=512

[status/16]
Size=16
Context=Status
Type=Scalable
MinSize=8
MaxSize=22

[status/scalable]
Size=48
Context=Status
Type=Scalable
MinSize=23
MaxSize=512

[breeze/actions/16]
Size=16
Context=Actions
Type=Fixed

[breeze/actions/22]
Size=22
Context=Actions
Type=Fixed

[breeze/actions/24]
Size=24
Context=Actions
Type=Fixed

[breeze/actions/32]
Size=32
Context=Actions
Type=Scalable
MinSize=32
MaxSize=256

[breeze/applets/48]
Size=48
Context=Status
Type=Scalable
MinSize=32
MaxSize=256

[breeze/apps/16]
Size=16
Context=Applications
Type=Fixed

[breeze/apps/22]
Size=22
Context=Applications
Type=Fixed

[breeze/apps/32]
Size=32
Context=Applications
Type=Fixed

[breeze/categories/22]
Size=22
Context=Categories
Type=Fixed

[breeze/devices/16]
Size=16
Context=Devices
Type=Fixed

[breeze/devices/22]
Size=22
Context=Devices
Type=Fixed

[breeze/devices/32]
Size=32
Context=Devices
Type=Fixed

[breeze/emotes/22]
Size=22
Context=Emotes
Type=Fixed

[breeze/mimetypes/16]
Size=16
Context=MimeTypes
Type=Fixed
MinSize=16

[breeze/mimetypes/22]
Size=22
Context=MimeTypes
Type=Scalable
MinSize=22
MaxSize=24

[breeze/mimetypes/32]
Size=32
Context=MimeTypes
Type=Fixed

[breeze/mimetypes/64]
Size=64
Context=MimeTypes
Type=Scalable
MinSize=64
MaxSize=256

[breeze/places/16]
Size=16
Context=Places
Type=Fixed
MinSize=16

[breeze/places/22]
Size=22
Context=Places
Type=Fixed

[breeze/preferences/22]
Size=22
Context=Applications
Type=Fixed

[breeze/preferences/32]
Size=32
Context=Applications
Type=Scalable
MinSize=32
MaxSize=256

[breeze/status/16]
Size=16
Context=Status
Type=Fixed

[breeze/status/22]
Size=22
Context=Status
Type=Fixed

[breeze/status/24]
Size=24
Context=Status
Type=Fixed

[breeze/status/32]
Size=32
Context=Status
Type=Fixed
